version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - skip-changelog
  - dependencies
  ignore:
  - dependency-name: pytest
    versions:
    - "> 6.0.0, < 6.1"
  - dependency-name: pytest
    versions:
    - "> 6.1.0, < 6.2"
  - dependency-name: pytest
    versions:
    - "> 6.2.0, < 6.3"
  - dependency-name: scrapy
    versions:
    - ">= 1.8.a, < 1.9"
  rebase-strategy: disabled
